//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_App_Crud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Aluno
    {
        
        public int AlunoID { get; set; }
        [Display(Name = "Nome do Aluno")]
        [Required]
        public string AlunoNome { get; set; }
        [Display(Name = "Departamento")]
        [Required]
        public int DepartamentoID { get; set; }
        [Display(Name = "Assunto")]
        [Required]
        public int AssuntoID { get; set; }
    
        public virtual Assunto Assunto { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
