//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Abtra_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaAbtra
    {
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public System.DateTime DataDeNascimento { get; set; }
        public string Sexo { get; set; }
        public string CPF { get; set; }
        public string Endereço { get; set; }
        public int Numero { get; set; }
        public string Telefone { get; set; }
        public string CEP { get; set; }
        public System.DateTime FichaDeCadastro { get; set; }
    }
}
