//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FechadoParaManutenção.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Abtra_Es_ProjectEntities : DbContext
    {
        public Abtra_Es_ProjectEntities()
            : base("name=Abtra_Es_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assunto> Assunto { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<TabAbtra> TabAbtra { get; set; }
    }
}
