//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FechadoParaManutenção.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TabAbtra
    {
        [Required]
        [Display(Name = "Oi")]
        public int AlunoId { get; set; }
        [Required]
        [Display(Name = "Oi")]
        public string AlunoNome { get; set; }
        public int CPF { get; set; }
        public int DataDeNascimento { get; set; }
        public int DepartamentoID { get; set; }
        public int AssuntoID { get; set; }
    
        public virtual Assunto Assunto { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
